version: '3.8'

services:
  pyinv-auto:
    build: .
    container_name: pyinv-auto
    volumes:
      # Mount C:\Invoices to container's /app/invoices
      - C:\Invoices:/app/invoices
      # Mount C:\Results for CSV output
      - C:\Results:/app/output
      # Mount logs for debugging
      - ./logs:/app/logs
    environment:
      # Optional: Override config via environment variables
      - PYTHONUNBUFFERED=1
    # For watch mode (continuous monitoring):
    # command: python pyinv_auto.py
    # restart: unless-stopped
    # For process-only mode (default - run once and exit):
    command: python pyinv_auto.py --watch-folder /app/invoices --output /app/output/invoices_parsed.csv --process-only
